// truck-fleet/src/app/[locale]/components/Header.tsx
import LanguageSelector from "@/components/settings/LanguageSelector";
import { ThemeToggle } from "@/components/settings/ThemeToggle";
import { Button } from "@/components/ui/button";
import { Link } from "@/i18n/routing";
import { cn } from "@/lib/utils";
import { IconPackages } from "@tabler/icons-react";
import { motion, type Variants } from "motion/react";
import React from "react";
import { useTranslations } from "next-intl";

const itemVariants: Variants = {
	hidden: { opacity: 0, y: -20, filter: "blur(15px)" },
	visible: {
		opacity: 1,
		y: 0,
		filter: "blur(0px)",
		scale: 1,
		transition: {
			y: { duration: 0.3 },
			opacity: { duration: 0.4 },
			filter: { duration: 0.3 },
		},
	},
};

export default function Header() {
	const [isScrolled, setIsScrolled] = React.useState(false);
	const t = useTranslations("");

	React.useEffect(() => {
		const handleScroll = () => {
			setIsScrolled(window.scrollY > 25);
		};

		window.addEventListener("scroll", handleScroll);
		return () => window.removeEventListener("scroll", handleScroll);
	}, []);

	const handleSectionClick = (
		e: React.MouseEvent<HTMLAnchorElement>,
		sectionId: string,
	) => {
		e.preventDefault();
		const element = document.querySelector(sectionId);
		if (element) {
			setTimeout(() => {
				element.scrollIntoView({ behavior: "smooth", block: "start" });
			}, 100);
		}
	};

	const sections = [
		{
			link: "#problem",
			label: t("problem.title"),
		},
		{
			link: "#solution",
			label: t("solution.title"),
		},
		{
			link: "#mobile-app",
			label: t("mobileApp.title"),
		},
		{
			link: "#pricing",
			label: t("pricing.title"),
		},
		// {
		// 	link: "#features",
		// 	label: t("features"),
		// },
		// {
		// 	link: "#fleet",
		// 	label: t("fleet"),
		// },
		// {
		// 	link: "#analytics",
		// 	label: t("analytics"),
		// },
	];

	return (
		<>
			<motion.div
				initial="hidden"
				animate="visible"
				transition={{
					staggerChildren: 0.1,
				}}
				className={cn(
					"fixed top-0 right-0 left-0 z-50 mx-auto my-5 w-full rounded-3xl border px-6 py-4 transition-all duration-300 ease-out-quart shadow-[0px_0px_10px_0px_rgba(0,0,0,0.1)] ",
					isScrolled &&
						"max-w-7xl border-primary/20 bg-background/50 backdrop-blur-lg shadow-primary/20",
					!isScrolled &&
						"max-w-[90%] border-transparent bg-background/0 backdrop-blur-none shadow-transparent",
				)}
			>
				<div className="flex items-center justify-between">
					<motion.h1
						onClick={() => {
							window.scrollTo({ top: 0, behavior: "smooth" });
						}}
						variants={itemVariants}
						className="flex cursor-pointer items-center gap-2 font-sans font-semibold text-2xl"
					>
						<IconPackages size={32} className="size-8" />
						Truck Fleet
					</motion.h1>
					<div className="flex gap-4">
						{sections.map((section, index) => (
							<motion.div key={section.label} variants={itemVariants}>
								<Link
									href={section.link}
									onClick={(e) => handleSectionClick(e, section.link)}
								>
									<Button variant="linkHover2" size={"lg"} className="text-lg">
										{section.label}
									</Button>
								</Link>
							</motion.div>
						))}
					</div>
					<div className="flex items-center gap-2">
						<motion.div variants={itemVariants}>
							<ThemeToggle className="rounded-2xl" />
						</motion.div>
						<motion.div variants={itemVariants}>
							<LanguageSelector className="rounded-2xl" />
						</motion.div>
						<motion.div variants={itemVariants}>
							<Link href="/login" prefetch>
								<Button variant="default" className="">
									Sign in
								</Button>
							</Link>
						</motion.div>
					</div>
				</div>
			</motion.div>
		</>
	);
}

// truck-fleet/components/Landing/Header.vue
<script lang="ts" setup>
function goToSection(id: string) {
  const element = document.getElementById(id);
  element?.scrollIntoView({ behavior: "smooth" });
}

onMounted(() => {
  animate(
    ".link-button",
    {
      y: [-50, 0],
      scale: [0.6, 1.1, 1],
      opacity: [0, 1],
      filter: ["blur(15px)", "blur(0px)"],
    },
    {
      delay: stagger(0.07, {
        start: 0.3,
      }),
      easing: spring({
        damping: 15,
        stiffness: 100,
        mass: 0.7,
      }),
    },
  );
});
</script>

<template>
  <div class="absolute top-3 flex w-full justify-center">
    <Motion
      class="flex-[0.7]"
      :initial="{
        scale: 0.5,
        opacity: 0,
        y: -150,
        filter: 'blur(15px)',
      }"
      :animate="{
        scale: 1,
        opacity: 1,
        y: 0,
        filter: 'blur(0px)',
      }"
      :transition="{
        easing: spring({
          damping: 15,
          stiffness: 100,
          mass: 0.5,
        }),
      }"
      :tag="'header'"
    >
      <div
        class="flex h-16 select-none items-center justify-between gap-3 overflow-hidden rounded-lg border border-white/15 bg-gray-900/50 px-2 shadow-lg shadow-white/20 backdrop-blur-xl"
      >
        <NuxtImg src="/logo-dark.svg" alt="Truck Fleet Logo" />
        <Button class="link-button" variant="link">Product</Button>
        <Button class="link-button" variant="link">Pricing</Button>
        <Button class="link-button" variant="link">About</Button>
        <div class="flex flex-1 items-center justify-end gap-3">
          <NuxtLink href="/login" as-child>
            <Button variant="outline">Get Started</Button>
          </NuxtLink>
        </div>
      </div>
    </Motion>
  </div>
</template>

<style lang="scss"></style>
