// truck-fleet/src/app/[locale]/dashboard/orders/components/TruckTabs.tsx
"use client";
import { useEffect, useState } from "react";
// import { usePathname, useRouter } from "next/navigation";

import AnimatedTabs from "@/components/AnimatedTabs";
import { db } from "@/firebase/firebase";
import useCompanyId from "@/hooks/useCompanyId";
import { usePathname, useRouter } from "@/lib/navigation";
import { collection, query, where } from "firebase/firestore";
import { useCollectionData } from "react-firebase-hooks/firestore";

export default function TruckTabs() {
	const router = useRouter();
	const pathName = usePathname();
	const [tabs, setTabs] = useState([""]);

	const { companyId } = useCompanyId();

	const [values, loading, error, snapshot] = useCollectionData<any>(
		query(collection(db, "trucks"), where("companyId", "==", companyId)),
		{},
	);

	useEffect(() => {
		if (values === undefined || values.length === 0 || loading) return;

		setTabs(values?.map((truck) => truck.licensePlate) || []);

		if (pathName === "/dashboard/orders")
			router.replace(`/dashboard/orders/${values?.[0]?.licensePlate}`);
	}, [values, loading, pathName, router.replace]);

	const [currentSelectedTab, setCurrentTab] = useState(tabs[0]);

	useEffect(() => {
		setCurrentTab(tabs.find((tab) => pathName.includes(tab)) || tabs[0]);
	}, [pathName, tabs]);

	return (
		<div className="flex h-10 flex-row gap-2">
			<AnimatedTabs
				tabs={tabs.map((tab) => ({
					label: tab,
					value: `/dashboard/orders/${tab}`,
				}))}
			/>
		</div>
	);
}

// truck-fleet/components/Order/TruckTabs.vue
<script setup lang='ts'>
import { collection, query, where } from 'firebase/firestore';

const db = useFirestore();

const auth = useFirebaseAuth();

await auth?.authStateReady();

const {
  data: profile,
  promise
} = await useProfileDoc();

await promise.value;
let id = profile.value!.type === 'speditor' ? profile.value!.companyId : profile.value!.id;


const {
  data: trucks,
  pending,
  error
} = useCollection(query(collection(db, 'trucks'), where('companyId', '==', id)));

// Create the links for every truck

const links = computed(() =>
  [
    {
      label: 'All',
      to: '/dashboard/orders/all'
    },
    ...trucks.value?.map((truck: any) => ({
      label: truck.licensePlate,
      to: `/dashboard/orders/${truck.licensePlate}`
    })),

  ]
);
</script>

<template>
  <div>

    <div v-if="pending">Loading...</div>
    <div v-if="error">{{ error.message }}</div>

    <div v-if="!pending && !trucks.length">No trucks found</div>


    <UHorizontalNavigation :links />

  </div>
</template>
